"""empty message

Revision ID: 159b479920da
Revises: 5ebaecf6d8b2
Create Date: 2023-10-29 19:04:48.676778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159b479920da'
down_revision = '5ebaecf6d8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
